#!/usr/bin/env python3

# Quick validation of the generated JSONL file
import json

try:
    # Check the file generated by the test
    with open("PublicnEUro_test.jsonl", "r", encoding='utf-8') as f:
        content = f.read()
        data = json.loads(content)
    
    print("✅ Generated JSONL file is valid JSON")
    
    # Check for problematic values
    content_str = str(data)
    if "NaN" in content_str:
        print("❌ Found NaN values")
    else:
        print("✅ No NaN values found")
    
    if '"n.a."' in content_str:
        print("❌ Found n.a. values")
    else:
        print("✅ No n.a. values found")
    
    # Check funding specifically
    if 'funding' in data and data['funding']:
        print(f"\nFunding entries ({len(data['funding'])}):")
        for i, fund in enumerate(data['funding']):
            name = fund.get('name', 'N/A')
            identifier = fund.get('identifier', 'No identifier provided')
            print(f"  {i+1}. {name} - {identifier}")
    
    print("\n✅ JSONL validation completed successfully!")
    
except Exception as e:
    print(f"❌ Error: {e}")
